spring:
  application:
    name: burble
  datasource:
    url: jdbc:h2:mem:burble;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

burble:
  ontology:
    persistance:
      world: h2

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized


